datasets:
  flickr_CaptionToPhrase:
    data_type: images
    build_info:
      image_path: /root/autodl-tmp/filtered_flickr/filtered_flickr/images
      ann_path: /root/autodl-tmp/filtered_flickr/filtered_flickr/captiontobbox.json
