datasets:
  flickr_grounded_caption:
    data_type: images
    build_info:
      image_path: /mnt/share/mllm_data/original_data/FilteredFlickr-30k/flickr30k-images
      ann_path: /mnt/share/mllm_data/original_data/FilteredFlickr-30k/groundedcaption.json
