datasets:
  llava_detail:
    data_type: images
    build_info:
      image_path: /mnt/share/mllm_data/original_data/COCO2014/train2014
      ann_path: /mnt/share/mllm_data/original_data/LLaVA/detail_23k.json