datasets:
  textcaps_caption:
    data_type: images
    
    build_info:
      image_path: /mnt/share/mllm_data/original_data/TextCaps/train_images
      ann_path: /mnt/share/mllm_data/original_data/TextCaps/TextCaps_0.1_train.json


